# Generated by Django 3.1.7 on 2021-05-01 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_nation', '0005_auto_20210412_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uploaded_on',
            field=models.DateField(default=datetime.datetime(2021, 5, 1, 18, 14, 4, 642501)),
        ),
    ]
